### ISSUE TITLE
afile bug

### ISSUE THREAD

**Issue by qwert159784623** [SeisNN/SeisNN#49]
**Describe the bug**
reading afile has an error with arrival time 0.000 second 

**bug description**
afile 中到時0.000秒代表沒有挑時間，而不是0.000秒時有到時

**Expected behavior**
這種在LABEL上不應出現PICK

**Screenshots**
![image](https://user-images.githubusercontent.com/61823789/119955601-c7bcab00-bfd2-11eb-88fd-11a46cf4ccc3.png)

**Additional context**

**Comment by jimmy60504** [comment]
![圖片](https://user-images.githubusercontent.com/11827839/120151397-c8498180-c21e-11eb-86fe-73c2c554a155.png)

因為 A file 的 0.00 sec 代表沒有 pick
但因為畫 pick 是 pick 秒數 + 資料開始秒數
所以才會在開始的地方有 pick
