### ISSUE TITLE
Continuous data input 

### ISSUE THREAD

**Issue by jimmy60504** [SeisNN/SeisNN#50]
**Is your feature request related to a problem? Please describe.**
為了在測站資料中掃描地震事件，需要讀取沒有 pick 的連續資料

**Describe the solution you'd like**
將所選的測站範圍內，依照給定的時間範圍每 30 秒切割一次。

**Describe alternatives you've considered**
由於資料擷取長度是 3008 個點，所以每個時間窗向前推進 30 秒整的話會稍微重疊 8 個資料點，雖然比其他研究重疊一半少蠻多的。

**Comment by qwert159784623** [comment]
能夠照30秒切一次並將預測結果畫出來。
下一步要思考如何存入模型預測的PICK，並且與現有的到時做比較 
下列為間距30秒範例，但每30秒會進行一次normalize，因此波型看起來沒有接得很好
不確定這樣是不是合理的
![image](https://user-images.githubusercontent.com/61823789/120265369-7eba6e80-c2d2-11eb-81d2-dfc22074889a.png)
![image](https://user-images.githubusercontent.com/61823789/120265376-82e68c00-c2d2-11eb-88eb-fdbdce535c3d.png)
![image](https://user-images.githubusercontent.com/61823789/120265382-8712a980-c2d2-11eb-8605-89b2f1815b43.png)

**Comment by qwert159784623** [comment]
重疊的0.08秒(8個資料點)不確定有沒有重疊到，從資料的起始時間來看好像沒有重疊的樣子

**Comment by jimmy60504** [comment]
如果沒有重疊到我覺得應該影響不大吧，就先能切30秒再說。

**Comment by qwert159784623** [comment]
原本的方法從 Archive 每30秒拉一次資料，且分別經過模型預測的時間太長，效率不高
改為一次拉很長的時間段，再用間距30秒的Window掃過，把input組成一個大一點的batch一次通過模型

**Comment by qwert159784623** [comment]
目前能夠從SDS_ROOT中的資料已日為單位自己找出資料起始點，且將預測出來的PICK放入database
但因模型的關係，noise產生出非常大量的pick
