### ISSUE TITLE
generate_tfrecord replace by zeros

### ISSUE THREAD

**Issue by qwert159784623** [SeisNN/SeisNN#65]
**Describe the bug**
CWB資料產生出來的TFRecord會常常有突然斷掉剩下都被0補起來的現象

CWB資料為不連續資料
1.假設資料長度從01:15:33_01:16:12長39秒
2.若依照P波挑速度並且隨機位移選擇到的時間比起時時間更早的話，取到的資料會不足30秒，舉例來說若隨機到的時間為01:15:23_01:15:53，從CWB_mseed取到的波型會只有01:15:33~01:15:53長20秒，剩下空的10秒鐘便會被0取代，變成我們看到的從中間斷掉的樣子

**Screenshots**
![image](https://user-images.githubusercontent.com/61823789/120902427-fbeb3800-c672-11eb-8276-7e251db63203.png)
![image](https://user-images.githubusercontent.com/61823789/120902434-04dc0980-c673-11eb-9751-34b0bd03e154.png)
此兩張圖應該為接起來的，但是會因為上述原因斷掉，並且形成假的S波label.

**Comment by qwert159784623** [comment]
在資料處理過程中加入 stream.trim() 此問題應該是解決了，目前正在製作新的 TFRecord

**Comment by qwert159784623** [comment]
這個部分處理完了!!

**Comment by jimmy60504** [comment]
有關聯的 PR 嗎？可以點一下喔～

**Comment by jimmy60504** [comment]
code 已經合併到 master，所以結案
